services:
  api:
    container_name: actfast-api
    build:
        context: .
        dockerfile: Dockerfile
    cpus: 1
    mem_limit: 200m
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Los_Angeles
    pull_policy: build
